spring:
  application:
    name: songdo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DEV_MYSQL_HOST}:${DEV_MYSQL_PORT}/${DEV_MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DEV_DATABASE_USERNAME}
    password: ${DEV_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

toss:
  payments:
    client-key: test_ck_ma60RZblrqNevMlKYBgM8wzYWBn1
    secret-key: test_ck_ma60RZblrqNevMlKYBgM8wzYWBn1
    base-url: https://api.tosspayments.com
